---
- name: Setup kubeconfig for non-root users
  hosts: kube_control_plane
  become: true
  vars:
    kube_users:
      - kvenkata
  
  tasks:
    - name: Create .kube directory for users
      file:
        path: "/home/{{ item }}/.kube"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0755'
      loop: "{{ kube_users }}"

    - name: Copy admin kubeconfig to user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ item }}/.kube/config"
        remote_src: yes
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0600'
      loop: "{{ kube_users }}"

    - name: Verify kubeconfig works
      shell: kubectl get nodes
      become_user: "{{ item }}"
      register: kubectl_test
      loop: "{{ kube_users }}"
      
    - name: Show kubectl result
      debug:
        msg: "{{ kubectl_test.results }}"